"""empty message

Revision ID: 0aa4710debef
Revises: 31673a81a52e
Create Date: 2024-10-16 00:26:23.440565

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0aa4710debef'
down_revision = '31673a81a52e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('character', schema=None) as batch_op:
        batch_op.drop_column('skin_color')

    with op.batch_alter_table('favorite', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category', sa.String(length=250), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorite', schema=None) as batch_op:
        batch_op.drop_column('category')

    with op.batch_alter_table('character', schema=None) as batch_op:
        batch_op.add_column(sa.Column('skin_color', sa.VARCHAR(length=250), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
